### ISSUE TITLE
Possible error in add on link

### ISSUE THREAD

**Issue by axk4545** [thenaterhood/thenaterhood.github.io#2]
The below lines appear to point to an incorrect link. I am not sure if you intended to use ublock or ublock origin. If this was intentional please ignore.
Link to post is [https://thenaterhood.com/blog/read/2017.03.30.htm/](https://thenaterhood.com/blog/read/2017.03.30.htm/)

`This is often not a known problem for the layperson, but it can become one when a quick search results in a month of banner ads for something embarrassing (or amusing to the people sitting nearby on public transit). There are relatively easy ways to prevent this sort of tracking - <a href="https://www.ublock.org/">browser add-ons such as ublock can be installed that block most tracking services</a>.</p>`

**Comment by thenaterhood** [comment]
💯 
Fixed.
